name: create clash rule providers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: create rule providers
        run: |
          git checkout master
          sed -i "/,/ s/^/  - /" $(find ./ -name "*.list"|grep -v " ")
          sed -i "/#/ s/^/  /" $(find ./ -name "*.list"|grep -v " ")
          sed -i "1i\payload:" $(find ./ -name "*.list"|grep -v " ")
          sed -i "/USER-AGENT/d" $(find ./ -name "*.list"|grep -v " ")
          # sed -i "/PROCESS-NAME/d" $(find ./ -name "*.list"|grep -v " ")
          sed -i "/URL-REGEX/d" $(find ./ -name "*.list"|grep -v " ")
          sed -i "/IP-CIDR/ s/\(.*\),\(.*\),.*/\1,\2/gp" $(find ./ -name "*.list"|grep -v " ")
          for i in $(find ./ -name "*.list"||grep -v " "|awk -F'.' '{print "."$2}'); do mv $i.list $i.yaml; done

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
