name: create clash rule providers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: create rule providers
        shell: bash
        run: |
          git checkout master
          LIST=$(find ./ -name "*.yaml"|grep -v "cidr"|grep -Ev "Domain|CIDR"|awk -F "." '{print $1"."$2}')
          for i in $LIST; do grep "IP-CIDR" $i.yaml > $i-CIDR.yaml; done
          for i in $LIST; do grep -v "IP-CIDR" $i.yaml > $i-Domain.yaml; done
          DOMAIN_LIST=$(find ./ -name "*-Domain.yaml")
          for i in ${DOMAIN_LIST}; do sed -i "s/DOMAIN,//g" $i; done
          for i in ${DOMAIN_LIST}; do sed -i "s/  - /  - '/g" $i; done
          for i in ${DOMAIN_LIST}; do sed -i "s/$/'/g" $i; done
          
          CIDR_LIST=$(find ./ -name "*-CIDR.yaml")
          for i in ${CIDR_LIST}; do sed -i "s/IP-CIDR,//g" $i; done
          for i in ${CIDR_LIST}; do sed -i "s/,no-resolve//g" $i; done
          for i in ${CIDR_LIST}; do sed -i "s/  - /  - '/g" $i; done
          for i in ${CIDR_LIST}; do sed -i "s/$/'/g" $i; done
          for i in ${CIDR_LIST}; do sed -i "1i\payload:" $i; done

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
