name: purge jsdelivr

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: purge jsdelivr
        shell: bash
        run: |
          git checkout gh-pages
          LIST=$(ls -l Clash-RuleSet-Classical/*.yaml|awk '{print $NF}')
          for i in $LIST; do curl https://purge.jsdelivr.net/gh/yangchuansheng/Rules/@gh-pages$i; done
          LIST=$(ls -l Clash-RuleSet-Classical/Special/*.yaml|awk '{print $NF}')
          for i in $LIST; do curl https://purge.jsdelivr.net/gh/yangchuansheng/Rules/@gh-pages$i; done
          LIST=$(ls -l Clash-RuleSet-Classical/PROXY/*.yaml|awk '{print $NF}')
          for i in $LIST; do curl https://purge.jsdelivr.net/gh/yangchuansheng/Rules/@gh-pages$i; done
          
          LIST=$(ls -l *.list|awk '{print $NF}')
          for i in $LIST; do curl https://purge.jsdelivr.net/gh/yangchuansheng/Rules/@gh-pages$i; done
          LIST=$(ls -l Special/*.list|awk '{print $NF}')
          for i in $LIST; do curl https://purge.jsdelivr.net/gh/yangchuansheng/Rules/@gh-pages$i; done
          LIST=$(ls -l PROXY/*.list|awk '{print $NF}')
          for i in $LIST; do curl https://purge.jsdelivr.net/gh/yangchuansheng/Rules/@gh-pages$i; done
